COMPREHENSIVE_UNIVERSITIES = {
    # ============================================
    # USA - IVY LEAGUE UNIVERSITIES (8)
    # ============================================
    "harvard university",
    "yale university",
    "princeton university",
    "columbia university",
    "university of pennsylvania",
    "cornell university",
    "brown university",
    "dartmouth college",

    # ============================================
    # USA - TOP PRIVATE UNIVERSITIES (50+)
    # ============================================
    "massachusetts institute of technology",
    "stanford university",
    "california institute of technology",
    "duke university",
    "northwestern university",
    "johns hopkins university",
    "university of chicago",
    "rice university",
    "vanderbilt university",
    "washington university in st louis",
    "emory university",
    "georgetown university",
    "carnegie mellon university",
    "university of notre dame",
    "new york university",
    "university of southern california",
    "boston university",
    "boston college",
    "brandeis university",
    "tufts university",
    "case western reserve university",
    "northeastern university",
    "rensselaer polytechnic institute",
    "tulane university",
    "wake forest university",
    "lehigh university",
    "syracuse university",
    "pepperdine university",
    "fordham university",
    "george washington university",
    "american university",
    "southern methodist university",
    "university of miami",
    "clark university",
    "worcester polytechnic institute",
    "university of rochester",
    "brigham young university",
    "claremont mckenna college",
    "pomona college",
    "williams college",
    "amherst college",
    "swarthmore college",

    # ============================================
    # USA - UC SYSTEM (10)
    # ============================================
    "university of california berkeley",
    "university of california los angeles",
    "university of california san diego",
    "university of california santa barbara",
    "university of california irvine",
    "university of california davis",
    "university of california santa cruz",
    "university of california riverside",
    "university of california merced",
    "university of california san francisco",

    # ============================================
    # USA - MAJOR STATE UNIVERSITIES (100+)
    # ============================================
    "university of michigan ann arbor",
    "university of virginia",
    "university of north carolina chapel hill",
    "georgia institute of technology",
    "university of illinois urbana champaign",
    "university of wisconsin madison",
    "university of texas at austin",
    "university of washington",
    "university of florida",
    "ohio state university",
    "pennsylvania state university",
    "purdue university",
    "university of maryland college park",
    "university of minnesota twin cities",
    "rutgers university",
    "texas a&m university",
    "university of pittsburgh",
    "michigan state university",
    "indiana university bloomington",
    "university of iowa",
    "university of georgia",
    "university of arizona",
    "arizona state university",
    "university of colorado boulder",
    "university of massachusetts amherst",
    "university of connecticut",
    "university of delaware",
    "virginia tech",
    "north carolina state university",
    "clemson university",
    "colorado state university",
    "florida state university",
    "iowa state university",
    "louisiana state university",
    "oregon state university",
    "university of alabama",
    "university of arkansas",
    "university of kentucky",
    "university of south carolina",
    "university of tennessee",
    "university of kansas",
    "university of missouri",
    "university of oklahoma",
    "university of oregon",
    "washington state university",
    "university of south florida",
    "university of central florida",
    "florida international university",
    "university of houston",
    "university of utah",
    "university of cincinnati",
    "university of illinois chicago",
    "university of nebraska lincoln",
    "kansas state university",
    "university of mississippi",
    "university of nebraska omaha",
    "university of nevada las vegas",
    "university of new mexico",
    "university of north texas",
    "university of oregon",
    "university of rhode island",
    "university of south alabama",
    "university of south dakota",
    "university of vermont",
    "university of wyoming",
    "west virginia university",

    # ============================================
    # USA - SUNY SYSTEM (10)
    # ============================================
    "stony brook university",
    "university at buffalo",
    "binghamton university",
    "university at albany",
    "suny geneseo",
    "suny new paltz",
    "suny purchase college",
    "suny plattsburgh",
    "suny cortland",
    "suny oneonta",

    # ============================================
    # USA - CAL STATE SYSTEM (20)
    # ============================================
    "san diego state university",
    "california state university long beach",
    "california state university fullerton",
    "california state polytechnic university pomona",
    "san jose state university",
    "california state university northridge",
    "california state university sacramento",
    "california polytechnic state university san luis obispo",
    "california state university chico",
    "california state university east bay",
    "california state university fresno",
    "california state university los angeles",
    "california state university monterey bay",
    "california state university san bernardino",
    "california state university san marcos",
    "california state university stanislaus",
    "humboldt state university",
    "california state university bakersfield",
    "california state university channel islands",
    "california state university dominguez hills",

    # ============================================
    # USA - SERVICE ACADEMIES + LIBERAL ARTS (30)
    # ============================================
    "united states military academy",
    "united states naval academy",
    "united states air force academy",
    "united states coast guard academy",
    "united states merchant marine academy",
    "wellesley college",
    "bowdoin college",
    "carleton college",
    "davidson college",
    "grinnell college",
    "hamilton college",
    "haverford college",
    "middlebury college",
    "vassar college",
    "colgate university",
    "harvey mudd college",
    "bates college",
    "colby college",
    "smith college",
    "oberlin college",
    "macalester college",
    "bryn mawr college",
    "barnard college",
    "mount holyoke college",
    "scripps college",
    "wesleyan university",
    "trinity college",
    "denison university",
    "kenyon college",
    "lafayette college",

    # ============================================
    # UK - OXBRIDGE + GOLDEN TRIANGLE (8)
    # ============================================
    "university of oxford",
    "university of cambridge",
    "university college london",
    "imperial college london",
    "kings college london",
    "london school of economics and political science",

    # ============================================
    # UK - RUSSELL GROUP (25)
    # ============================================
    "university of edinburgh",
    "university of manchester",
    "university of bristol",
    "university of warwick",
    "university of glasgow",
    "university of birmingham",
    "university of leeds",
    "university of southampton",
    "university of sheffield",
    "university of nottingham",
    "durham university",
    "university of st andrews",
    "university of exeter",
    "queen mary university of london",
    "newcastle university",
    "university of york",
    "cardiff university",
    "university of liverpool",
    "university of leicester",
    "university of aberdeen",
    "queens university belfast",
    "university of newcastle upon tyne",
    "university of queensland belfast",
    "university of reading",
    "university of southampton",

    # ============================================
    # UK - OTHER MAJOR UNIVERSITIES (50)
    # ============================================
    "university of bath",
    "loughborough university",
    "lancaster university",
    "university of surrey",
    "university of sussex",
    "university of east anglia",
    "university of strathclyde",
    "university of dundee",
    "heriot watt university",
    "royal holloway university of london",
    "university of essex",
    "swansea university",
    "university of kent",
    "aston university",
    "bournemouth university",
    "university of portsmouth",
    "university of plymouth",
    "keele university",
    "university of hull",
    "oxford brookes university",
    "nottingham trent university",
    "sheffield hallam university",
    "manchester metropolitan university",
    "coventry university",
    "de montfort university",
    "university of bradford",
    "university of brighton",
    "university of hertfordshire",
    "city university of london",
    "brunel university london",
    "goldsmiths university of london",
    "soas university of london",
    "birbeck university of london",
    "university of stirling",
    "edinburgh napier university",
    "glasgow caledonian university",
    "robert gordon university",
    "ulster university",
    "aberystwyth university",
    "bangor university",
    "university of westminster",
    "middlesex university",
    "university of west london",
    "university of central lancashire",
    "university of huddersfield",
    "sheffield hallam university",
    "lincoln university",
    "university of roehampton",
    "canterbury christ church university",

    # ============================================
    # CANADA - U15 + MAJOR UNIVERSITIES (40)
    # ============================================
    "university of toronto",
    "university of british columbia",
    "mcgill university",
    "university of alberta",
    "universite de montreal",
    "mcmaster university",
    "university of waterloo",
    "university of calgary",
    "queens university",
    "western university",
    "university of ottawa",
    "dalhousie university",
    "university of saskatchewan",
    "university of manitoba",
    "universite laval",
    "simon fraser university",
    "university of victoria",
    "york university",
    "carleton university",
    "concordia university",
    "university of guelph",
    "university of windsor",
    "toronto metropolitan university",
    "university of regina",
    "memorial university of newfoundland",
    "university of new brunswick",
    "brock university",
    "lakehead university",
    "trent university",
    "wilfrid laurier university",
    "universite de sherbrooke",
    "universite du quebec a montreal",
    "university of northern british columbia",
    "mount allison university",
    "acadia university",
    "saint marys university",
    "st francis xavier university",
    "bishops university",
    "university of prince edward island",

    # ============================================
    # INDIA - IITs (23)
    # ============================================
    "indian institute of technology bombay",
    "indian institute of technology delhi",
    "indian institute of technology madras",
    "indian institute of technology kanpur",
    "indian institute of technology kharagpur",
    "indian institute of technology roorkee",
    "indian institute of technology guwahati",
    "indian institute of technology hyderabad",
    "indian institute of technology indore",
    "indian institute of technology bhu varanasi",
    "indian institute of technology ropar",
    "indian institute of technology patna",
    "indian institute of technology bhubaneswar",
    "indian institute of technology gandhinagar",
    "indian institute of technology jodhpur",
    "indian institute of technology mandi",
    "indian institute of technology palakkad",
    "indian institute of technology tirupati",
    "indian institute of technology dhanbad",
    "indian institute of technology bhilai",
    "indian institute of technology goa",
    "indian institute of technology jammu",
    "indian institute of technology dharwad",

    # ============================================
    # INDIA - IIMs (22)
    # ============================================
    "indian institute of management ahmedabad",
    "indian institute of management bangalore",
    "indian institute of management calcutta",
    "indian institute of management lucknow",
    "indian institute of management kozhikode",
    "indian institute of management indore",
    "indian institute of management shillong",
    "indian institute of management rohtak",
    "indian institute of management ranchi",
    "indian institute of management raipur",
    "indian institute of management tiruchirappalli",
    "indian institute of management kashipur",
    "indian institute of management udaipur",
    "indian institute of management nagpur",
    "indian institute of management visakhapatnam",
    "indian institute of management amritsar",
    "indian institute of management bodh gaya",
    "indian institute of management sambalpur",
    "indian institute of management sirmaur",
    "indian institute of management jammu",
    "indian institute of management mumbai",

    # ============================================
    # INDIA - NITs (31)
    # ============================================
    "national institute of technology tiruchirappalli",
    "national institute of technology karnataka surathkal",
    "national institute of technology rourkela",
    "national institute of technology warangal",
    "national institute of technology calicut",
    "national institute of technology durgapur",
    "national institute of technology kurukshetra",
    "national institute of technology silchar",
    "national institute of technology jamshedpur",
    "national institute of technology hamirpur",
    "dr b r ambedkar national institute of technology jalandhar",
    "national institute of technology raipur",
    "national institute of technology agartala",
    "motilal nehru national institute of technology allahabad",
    "maulana azad national institute of technology bhopal",
    "national institute of technology delhi",
    "national institute of technology goa",
    "malaviya national institute of technology jaipur",
    "national institute of technology manipur",
    "national institute of technology meghalaya",
    "national institute of technology mizoram",
    "national institute of technology nagaland",
    "visvesvaraya national institute of technology nagpur",
    "national institute of technology patna",
    "national institute of technology puducherry",
    "national institute of technology sikkim",
    "national institute of technology srinagar",
    "sardar vallabhbhai national institute of technology surat",
    "national institute of technology uttarakhand",
    "national institute of technology andhra pradesh",
    "national institute of technology arunachal pradesh"
}
